inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.8
  Exclude:
    - "bin/*"
    - "config/**/*"
    - 'vendor/**/*'

AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false