inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"

AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false