version: 2

jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Dockerコンテナのビルドと起動
          command: docker-compose up --build -d
      - run:
          name: DBの作成
          command: docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      - run:
          name: dbのマイグレーション
          command: docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run:
          name: ソースコードチェック
          command: docker-compose exec --env 'RAILS_ENV=test' web rubocop
      - run:
          name: テスト
          command: docker-compose exec --env 'RAILS_ENV=test' web rspec spec
workflows:
  version: 2
  build:
    jobs:
      - build:
        context:
          - portfolio-idimo